app/auth.py
"""Routes for user authentication."""
from flask import Blueprint, flash, redirect, render_template, request, url_for
from flask_login import current_user, login_user

from __init__ import login_manager
from forms import LoginForm, SignupForm
from models import User, db

# Blueprint Configuration
auth_bp = Blueprint(
    'auth_bp', __name__,
    template_folder='templates',
    static_folder='static'
)


@auth_bp.route('/signup', methods=['GET', 'POST'])
def signup():
    """
    User sign-up page.
    GET requests serve sign-up page.
    POST requests validate form & user creation.
    """
    form = SignupForm()
    if form.validate_on_submit():
        existing_user = User.query.filter_by(email=form.email.data).first()
        if existing_user is None:
            user = User(
                name=form.name.data,
                email=form.email.data,
                website=form.website.data
            )
            user.set_password(form.password.data)
            db.session.add(user)
            db.session.commit()  # Create new user
            login_user(user)  # Log in as newly created user
            return redirect(url_for('main_bp.dashboard'))
        flash('A user already exists with that email address.')
    return render_template(
        'signup.jinja2',
        title='Create an Account.',
        form=form,
        template='signup-page',
        body="Sign up for a user account."
    )


@auth_bp.route('/login', methods=['GET', 'POST'])
def login():
    """
    Log-in page for registered users.
    GET requests serve Log-in page.
    POST requests validate and redirect user to dashboard.
    """
    # Bypass if user is logged in
    if current_user.is_authenticated:
        return redirect(url_for('main_bp.dashboard'))

    form = LoginForm()
    # Validate login attempt
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and user.check_password(password=form.password.data):
            login_user(user)
            next_page = request.args.get('next')
            return redirect(next_page or url_for('main_bp.dashboard'))
        flash('Invalid username/password combination')
        return redirect(url_for('auth_bp.login'))
    return render_template(
        'login.jinja2',
        form=form,
        title='Log in.',
        template='login-page',
        body="Log in with your User account."
    )


@login_manager.user_loader
def load_user(user_id):
    """Check if user is logged-in upon page load."""
    if user_id is not None:
        return User.query.get(user_id)
    return None


@login_manager.unauthorized_handler
def unauthorized():
    """Redirect unauthorized users to Login page."""
    flash('You must be logged in to view that page.')
    return redirect(url_for('auth_bp.login'))

app/routes.py
import simplejson as json
from flask import current_app as app
from flask import Flask, request, Response, redirect, make_response
from flask import render_template, url_for, Blueprint, session
from flaskext.mysql import MySQL
from pymysql.cursors import DictCursor
from forms import ContactForm, SignupForm
import config
from flask_login import current_user, login_required, logout_user
from __init__ import mysql, sess
from assets import compile_auth_assets



'''
app = Flask(__name__, instance_relative_config=False)
app.config.from_object("config.Config")
app.config["RECAPTCHA_PUBLIC_KEY"] = "iubhiukfgjbkhfvgkdfm"
app.config["RECAPTCHA_PARAMETERS"] = {"size": "100%"}
#SECRET_KEY = os.urandom(32)
#app.config['SECRET_KEY'] = SECRET_KEY
mysql = MySQL(cursorclass=DictCursor)

app.config['MYSQL_DATABASE_HOST'] = 'db'
app.config['MYSQL_DATABASE_USER'] = 'root'
app.config['MYSQL_DATABASE_PASSWORD'] = 'root'
app.config['MYSQL_DATABASE_PORT'] = 3306
app.config['MYSQL_DATABASE_DB'] = 'citiesData'
mysql.init_app(app)
'''
#mysql = MySQL(cursorclass=DictCursor)
#mysql.init_app(app)

# Blueprint Configuration
main_bp = Blueprint(
    'main_bp',
    __name__,
    template_folder='templates',
    static_folder='static'
)
compile_auth_assets(app)


@app.route("/contact", methods=["GET", "POST"])
def contact():
    #"""Standard `contact` form."""
    form = ContactForm()
    if form.validate_on_submit():
        return redirect(url_for("success"))
    return render_template(
        "contact.html",
        form=form,
        template="form-template"
    )

@app.route("/signup", methods=["GET", "POST"])
def signup():
    """User sign-up form for account creation."""
    form = SignupForm()
    if form.validate_on_submit():
        return redirect(url_for("success"))
    return render_template(
        "signup.html",
        form=form,
        template="form-template",
        title="Signup Form"
    )

@app.route("/api/v2/test_response")
def users():
    headers = {"Content-Type": "application/json"}
    return make_response(
        'Part 4 - Testing Response Worked!',
        200,
        #headers=headers
    )

@app.errorhandler(404)
def not_found():
    """Page not found."""
    return make_response(render_template("404.html"), 404)

@app.errorhandler(400)
def bad_request():
    """Bad request."""
    return make_response(
        render_template("400.html"),
        400
    )

@app.errorhandler(500)
def server_error():
    """Internal server error."""
    return make_response(
        render_template("500.html"),
        500
    )

# Blueprint Configuration
main_bp = Blueprint(
    'main_bp', __name__,
    template_folder='templates',
    static_folder='static'
)


@main_bp.route('/', methods=['GET'])
@login_required
def dashboard():
    """Logged-in User Dashboard."""
    return render_template(
        'dashboard.jinja2',
        title='Flask-Login Tutorial.',
        template='dashboard-template',
        current_user=current_user,
        body="You are now logged in!"
    )


@main_bp.route("/logout")
@login_required
def logout():
    """User log-out logic."""
    logout_user()
    return redirect(url_for('auth_bp.login'))

@app.route('/', methods=['GET'])
def index():
    user = {'username': 'Johnny Pillacela'}
    cursor = mysql.get_db().cursor()
    cursor.execute('SELECT * FROM tblCitiesImport')
    result = cursor.fetchall()
    return render_template('index.html', title='Home', user=user, cities=result)


@app.route('/view/<int:city_id>', methods=['GET'])
def record_view(city_id):
    cursor = mysql.get_db().cursor()
    cursor.execute('SELECT * FROM tblCitiesImport WHERE id=%s', city_id)
    result = cursor.fetchall()
    return render_template('view.html', title='View Form', city=result[0])


@app.route('/edit/<int:city_id>', methods=['GET'])
def form_edit_get(city_id):
    cursor = mysql.get_db().cursor()
    cursor.execute('SELECT * FROM tblCitiesImport WHERE id=%s', city_id)
    result = cursor.fetchall()
    return render_template('edit.html', title='Edit Form', city=result[0])


@app.route('/edit/<int:city_id>', methods=['POST'])
def form_update_post(city_id):
    cursor = mysql.get_db().cursor()
    inputData = (request.form.get('fldName'), request.form.get('fldLat'), request.form.get('fldLong'),
                 request.form.get('fldCountry'), request.form.get('fldAbbreviation'),
                 request.form.get('fldCapitalStatus'), request.form.get('fldPopulation'), city_id)
    sql_update_query = """UPDATE tblCitiesImport t SET t.fldName = %s, t.fldLat = %s, t.fldLong = %s, t.fldCountry = 
    %s, t.fldAbbreviation = %s, t.fldCapitalStatus = %s, t.fldPopulation = %s WHERE t.id = %s """
    cursor.execute(sql_update_query, inputData)
    mysql.get_db().commit()
    return redirect("/", code=302)

@app.route('/cities/new', methods=['GET'])
def form_insert_get():
    return render_template('new.html', title='New City Form')


@app.route('/cities/new', methods=['POST'])
def form_insert_post():
    cursor = mysql.get_db().cursor()
    inputData = (request.form.get('fldName'), request.form.get('fldLat'), request.form.get('fldLong'),
                 request.form.get('fldCountry'), request.form.get('fldAbbreviation'),
                 request.form.get('fldCapitalStatus'), request.form.get('fldPopulation'))
    sql_insert_query = """INSERT INTO tblCitiesImport (fldName,fldLat,fldLong,fldCountry,fldAbbreviation,fldCapitalStatus,fldPopulation) VALUES (%s, %s,%s, %s,%s, %s,%s) """
    cursor.execute(sql_insert_query, inputData)
    mysql.get_db().commit()
    return redirect("/", code=302)

@app.route('/delete/<int:city_id>', methods=['POST'])
def form_delete_post(city_id):
    cursor = mysql.get_db().cursor()
    sql_delete_query = """DELETE FROM tblCitiesImport WHERE id = %s """
    cursor.execute(sql_delete_query, city_id)
    mysql.get_db().commit()
    return redirect("/", code=302)


@app.route('/api/v1/cities', methods=['GET'])
def api_browse() -> str:
    cursor = mysql.get_db().cursor()
    cursor.execute('SELECT * FROM tblCitiesImport')
    result = cursor.fetchall()
    json_result = json.dumps(result);
    resp = Response(json_result, status=200, mimetype='application/json')
    return resp


@app.route('/api/v1/cities/<int:city_id>', methods=['GET'])
def api_retrieve(city_id) -> str:
    cursor = mysql.get_db().cursor()
    cursor.execute('SELECT * FROM tblCitiesImport WHERE id=%s', city_id)
    result = cursor.fetchall()
    json_result = json.dumps(result);
    resp = Response(json_result, status=200, mimetype='application/json')
    return resp


@app.route('/api/v1/cities/<int:city_id>', methods=['PUT'])
def api_edit(city_id) -> str:
    cursor = mysql.get_db().cursor()
    content = request.json
    inputData = (content['fldName'], content['fldLat'], content['fldLong'],
                 content['fldCountry'], content['fldAbbreviation'],
                 content['fldCapitalStatus'], content['fldPopulation'],city_id)
    sql_update_query = """UPDATE tblCitiesImport t SET t.fldName = %s, t.fldLat = %s, t.fldLong = %s, t.fldCountry = 
        %s, t.fldAbbreviation = %s, t.fldCapitalStatus = %s, t.fldPopulation = %s WHERE t.id = %s """
    cursor.execute(sql_update_query, inputData)
    mysql.get_db().commit()
    resp = Response(status=200, mimetype='application/json')
    return resp

@app.route('/api/v1/cities', methods=['POST'])
def api_add() -> str:

    content = request.json

    cursor = mysql.get_db().cursor()
    inputData = (content['fldName'], content['fldLat'], content['fldLong'],
                 content['fldCountry'], content['fldAbbreviation'],
                 content['fldCapitalStatus'], request.form.get('fldPopulation'))
    sql_insert_query = """INSERT INTO tblCitiesImport (fldName,fldLat,fldLong,fldCountry,fldAbbreviation,fldCapitalStatus,fldPopulation) VALUES (%s, %s,%s, %s,%s, %s,%s) """
    cursor.execute(sql_insert_query, inputData)
    mysql.get_db().commit()
    resp = Response(status=201, mimetype='application/json')
    return resp

@app.route('/api/v1/cities/<int:city_id>', methods=['DELETE'])
def api_delete(city_id) -> str:
    cursor = mysql.get_db().cursor()
    sql_delete_query = """DELETE FROM tblCitiesImport WHERE id = %s """
    cursor.execute(sql_delete_query, city_id)
    mysql.get_db().commit()
    resp = Response(status=200, mimetype='application/json')
    return resp


@main_bp.route('/', methods=['GET'])
@login_required
def dashboard():
    """Logged in Dashboard screen."""
    session['redis_test'] = 'This is a session variable.'
    return render_template(
        'dashboard.jinja2',
        title='Flask-Session Tutorial.',
        template='dashboard-template',
        current_user=current_user,
        body="You are now logged in!"
    )


@main_bp.route('/session', methods=['GET'])
@login_required
def session_view():
    """Display session variable value."""
    return render_template(
        'session.html',
        title='Flask-Session Tutorial.',
        template='dashboard-template',
        session_variable=str(session['redis_test'])
    )

@main_bp.route("/logout")
@login_required
def logout():
    """User log-out logic."""
    logout_user()
    return redirect(url_for('auth_bp.login'))

#if __name__ == '__main__':
#   app.run(host='0.0.0.0', debug=True)

app/templates/contact.html
{% extends 'layout.html' %}

{% block styles %}
    <link
            rel="stylesheet"
            href="{{ url_for('static', filename='css/forms.css') }}"
            type="text/css"
    />
{% endblock %}


{% block content %}

  <div class="form-wrapper">
    <h2 class="title">Contact</h2>

    <form method="POST" action="{{ url_for('signup') }}">

      <fieldset class="form-field">
      {{ form.name.label }}
      {{ form.name }}
        {% if form.name.errors %}
        <ul class="errors">
          {% for error in form.name.errors %}
            <li>{{ error }}</li>
          {% endfor %}
        </ul>
        {% endif %}
      </fieldset>

      <fieldset class="form-field">
        {{ form.email.label }}
        {{ form.email }}
        {% if form.email.errors %}
          <ul class="errors">
            {% for error in form.email.errors %}
              <li>{{ error }}</li>
            {% endfor %}
          </ul>
        {% endif %}
      </fieldset>

      <fieldset class="form-field">
        {{ form.body.label }}
        {{ form.body }}
        {% if form.body.errors %}
          <ul class="errors">
            {% for error in form.body.errors %}
              <li>{{ error }}</li>
            {% endfor %}
          </ul>
        {% endif %}
      </fieldset>

      {{ form.submit }}

      </form>
  </div>

{% endblock %}

app/templates/dashboard.html
{% extends "layout.html" %}

{% block pagestyles %}
  <link href="{{ url_for('static', filename='dist/css/dashboard.css') }}" rel="stylesheet" type="text/css">
  <link rel="stylesheet" href="https://use.typekit.net/sus7rlu.css">
{% endblock %}

{% block content %}
  <h1>{{ body }}</h1>

  {% if current_user.is_authenticated %}
    <p>Hi {{ current_user.name }}!</p>
    <a href="{{ url_for('main_bp.logout') }}">Log out</a>
  {% endif %}

{% endblock %}

app/templates/edit.html
{% extends "layout.html" %}
{% block content %}
<form action="/edit/{{city.id}}" method="post">
    <div class="row">
        <div class="col">
            <label for="fldName">City Name</label>
            <input id="fldName" type="text" class="form-control" placeholder="City Name" name="fldName" value="{{city.fldName}}">
        </div>
        <div class="col">
            <label for="fldAbbreviation">City Abbreviation</label>
            <input id="fldAbbreviation" type="text" class="form-control" placeholder="City Abbreviation"
                   name="fldAbbreviation" value="{{city.fldAbbreviation}}">
        </div>
        <div class="col">
            <label for="fldCountry">City Country</label>
            <input id="fldCountry" type="text" class="form-control" placeholder="City Country" name="fldCountry" value="{{city.fldCountry}}">
        </div>
    </div>

    <div class="row">
        <div class="col">
            <label for="fldLat">City Latitude</label>
            <input id="fldLat" type="text" class="form-control" placeholder="City Latitude" name="fldLat" value="{{city.fldLat}}">
        </div>
        <div class="col">
            <label for="fldlong">City Longitude</label>
            <input id="fldlong" type="text" class="form-control" placeholder="City Longitude" name="fldLong" value="{{city.fldLong}}">
        </div>
    </div>
    <div class="row">
        <div class="col">
            <label for="fldCapitalStatus">Capital Status</label>

            <input id="fldCapitalStatus" type="text" class="form-control" placeholder="Capital Status"
                   name="fldCapitalStatus" value="{{city.fldCapitalStatus}}">
        </div>
        <div class="col">
            <label for="fldPopulation">City Population</label>
            <input id="fldPopulation" type="text" class="form-control" placeholder="Population" name="fldPopulation" value="{{city.fldPopulation}}">
        </div>
    </div>
    <button type="submit" class="btn btn-success">Save</button>

</form>
{% endblock %}

app/templates/index.html
{% extends "layout.html" %}
{% block content %}
<table class="table">
    <thead>
    <tr>
        <th scope="col">City Name</th>
        <th scope="col">Latitude</th>
        <th scope="col">Longitude</th>
        <th scope="col">Country</th>
        <th scope="col">Abbreviation</th>
        <th scope="col">Capital Status</th>
        <th scope="col">Population</th>
    </tr>
    </thead>
    <tbody>
    {% for city in cities %}
    <tr>
        <td><a href="view/{{city.id}}">{{ city.fldName }}</a></td>
        <td>{{ city.fldLat }}</td>
        <td>{{ city.fldLong }}</td>
        <td>{{ city.fldCountry }}</td>
        <td>{{ city.fldAbbreviation }}</td>
        <td>{{ city.fldCapitalStatus }}</td>
        <td>{{ city.fldPopulation }}</td>
    </tr>
    {% endfor %}
    </tbody>
</table>
{% endblock %}

app/templates/layout.html
<!doctype html>
<html lang="en">
<head>

    <!-- Required meta tags -->

    <!-- Bootstrap CSS -->


    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1, shrink-to-fit=no" name="viewport">
    <link crossorigin="anonymous" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" rel="stylesheet">
        {# Styles #}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}" type="text/css">
    <script src="https://kit.fontawesome.com/e3deaeba31.js" crossorigin="anonymous"></script>
    <link href="https://fonts.googleapis.com/css?family=Poppins:200,300,500" rel="stylesheet">
    {% block styles %}{% endblock %}
    {% if user %}
    <title>Welcome to {{ user.username }}'s site</title>
    {% else %}
    <title>Welcome to My Site!</title>
    {% endif %}
<head>
 <body>
<!-- As a heading -->


<nav class="navbar navbar-expand-lg navbar-light bg-light mb-1">
  <a class="navbar-brand" href="/">{% if user %}{{ user.username }}'s Homepage{% else %}
    <title>Welcome to My Homepage</title>
    {% endif %}</a>
  <button aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation" class="navbar-toggler" data-target="#navbarNavDropdown" data-toggle="collapse" type="button">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">
        <li class="nav-item active">
            <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item active">
            <a class="nav-link" href="/api/v1/cities">Cities API JSON endpoint <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item active">
            <a class="btn btn-success pl-2 lr-2 ml-3" href="/cities/new">Add +<span class="sr-only">(current)</span></a>
        </li>
    </ul>
  </div>
</nav>
<main class="container" role="main">
    <br>
    {% block content %}
    {% endblock %}
</main>
<div id="footer">
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script crossorigin="anonymous"
            integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
            src="https://code.jquery.com/jquery-3.4.1.slim.min.js"></script>
    <script crossorigin="anonymous"
            integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
            src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
    <script crossorigin="anonymous"
            integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
            src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
</div>
</body>
</html>

app/templates/login.html
{% extends "layout.html" %}

{% block pagestyles %}
  <link href="{{ url_for('static', filename='css/accounts.css') }}" rel="stylesheet" type="text/css">
{% endblock %}

{% block content %}
  <div class="form-wrapper">

    {% for message in get_flashed_messages() %}
      <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        {{ message }}
      </div>
    {% endfor %}

    <h1>Log In</h1>

    <form method="POST" action="/login">
      {{ form.csrf_token }}

      <fieldset class="email">
        {{ form.email.label }}
        {{ form.email(placeholder='youremail@example.com') }}
        {% if form.email.errors %}
          <ul class="errors">
            {% for error in form.email.errors %}
              <li>{{ error }}</li>{% endfor %}
          </ul>
        {% endif %}
      </fieldset>

      <fieldset class="password">
        {{ form.password.label }}
        {{ form.password }}
        {% if form.email.errors %}
          <ul class="errors">
            {% for error in form.password.errors %}
              <li>{{ error }}</li>{% endfor %}
          </ul>
        {% endif %}
      </fieldset>

      <div class="submit-button">
        {{ form.submit }}
      </div>

      <div class="login-signup">
        <span>Don't have an account? <a href="{{ url_for('auth_bp.signup') }}">Sign up.</a></span>
      </div>

    </form>
  </div>
{% endblock %}

app/templates/new.html
{% extends "layout.html" %}
{% block content %}
<form action="/cities/new" method="POST">
    <div class="row">
        <div class="col">
            <label for="fldName">City Name</label>
            <input id="fldName" type="text" class="form-control" placeholder="City Name" name="fldName">
        </div>
        <div class="col">
            <label for="fldAbbreviation">City Abbreviation</label>
            <input id="fldAbbreviation" t ype="text" class="form-control" placeholder="City Abbreviation"
                   name="fldAbbreviation">
        </div>
        <div class="col">
            <label for="fldCountry">City Country</label>
            <input id="fldCountry" type="text" class="form-control" placeholder="City Country" name="fldCountry">
        </div>
    </div>

    <div class="row">
        <div class="col">
            <label for="fldLat">City Latitude</label>
            <input id="fldLat" type="text" class="form-control" placeholder="City Latitude" name="fldLat">
        </div>
        <div class="col">
            <label for="fldlong">City Longitude</label>
            <input id="fldlong" type="text" class="form-control" placeholder="City Longitude" name="fldLong">
        </div>
    </div>
    <div class="row">
        <div class="col">
            <label for="fldCapitalStatus">Capital Status</label>

            <input id="fldCapitalStatus" type="text" class="form-control" placeholder="Capital Status "
                   name="fldCapitalStatus">
        </div>
        <div class="col">
            <label for="fldPopulation">City Population</label>
            <input id="fldPopulation" type="text" class="form-control" placeholder="Population" name="fldPopulation">
        </div>
    </div>
    <button type="submit" class="btn btn-success">Create</button>

</form>

{% endblock %}

app/templates/signup.html
{% extends 'layout.html' %}

{% block styles %}

    <link
        rel="stylesheet"
        href="{{ url_for('static', filename='css/forms.css') }}"
        type="text/css"
    />

{% endblock %}

{% block content %}

    <div class="form-wrapper">
      <h2 class="title">Sign Up</h2>

      <form method="POST" action="{{ url_for('signup') }}">
          {{ form.csrf_token }}

          <fieldset class="form-field">{{ form.email.label }} {{ form.email }}
            {% if form.email.errors %}
              <ul class="errors">
                {% for error in form.email.errors %}
                  <li class="error">
                      <i class="fas fa-exclamation"></i> <span class="error-message">{{ error }}</span>
                  </li>
                {% endfor %}
              </ul>
            {% endif %}
          </fieldset>

          <fieldset class="form-field">{{ form.password.label }} {{ form.password }}
            {% if form.password.errors %}
              <ul class="errors">
                {% for error in form.email.errors %}
                  <li class="error">
                      <i class="fas fa-exclamation"></i> <span class="error-message">{{ error }}</span>
                  </li>
                {% endfor %}
              </ul>
            {% endif %}
          </fieldset>

          <fieldset class="form-field">{{ form.confirmPassword.label }} {{ form.confirmPassword }}
            {% if form.confirmPassword.errors %}
              <ul class="errors">
                {% for error in form.email.errors %}
                  <li class="error">
                      <i class="fas fa-exclamation"></i> <span class="error-message">{{ error }}</span>
                  </li>
                {% endfor %}
              </ul>
            {% endif %}
          </fieldset>

          <fieldset class="form-field">{{ form.title.label }} {{ form.title }}
            <i class="fas fa-caret-down"></i>
            {% if form.title.errors %}
              <ul class="errors">
                {% for error in form.email.errors %}
                  <li class="error">
                      <i class="fas fa-exclamation"></i> <span class="error-message">{{ error }}</span>
                  </li>
                {% endfor %}
              </ul>
            {% endif %}
          </fieldset>

          <fieldset class="form-field">{{ form.website.label }} {{ form.website }}
            {% if form.website.errors %}
              <ul class="errors">
                {% for error in form.email.errors %}
                  <li class="error">
                      <i class="fas fa-exclamation"></i> <span class="error-message">{{ error }}</span>
                  </li>
                {% endfor %}
              </ul>
            {% endif %}
          </fieldset>

          <fieldset class="form-field">{{ form.birthday.label }} {{ form.birthday }}
            {% if form.birthday.errors %}
              <ul class="errors">
                {% for error in form.email.errors %}
                  <li class="error">
                      <i class="fas fa-exclamation"></i> <span class="error-message">{{ error }}</span>
                  </li>
                {% endfor %}
              </ul>
            {% endif %}
          </fieldset>

          {{ form.recaptcha }}
          {{ form.submit }}

      </form>
    </div>

{% endblock %}

app/templates/view.html
{% extends "layout.html" %}
{% block content %}

<div class="card" class="m-5 p-2">
    <h5 class="card-title" style="text-align: -webkit-left; padding-left: 20px; padding-top: 20px">{{ city.fldName }} - {{ city.fldAbbreviation }}</h5>

    <ul class="list-group list-group-flush">
        <li class="list-group-item">{{ city.fldLat }}</li>
        <li class="list-group-item">{{ city.fldLong }}</li>
        <li class="list-group-item">{{ city.fldCapitalStatus }}</li>
        <li class="list-group-item">{{ city.fldCountry }}</li>
        <li class="list-group-item">{{ city.fldPopulation }}</li>
    </ul>
    <div class="card-body">
        <a href="/edit/{{city.id}}" class="card-link btn btn-primary">Edit</a>
    </div>
</div>
<br>
<form action="/delete/{{city.id}}" method="post"><button type="submit" class="btn btn-danger">Delete</button></form>


{% endblock %}